name: "Deploy"
description: "Deploy to GKE Cluster using Skaffold"
inputs:
  gcp-project-id:
    description: "GCP Project ID"
    required: true
    default: "${{ secrets.GCP_PROJECT_ID }}"
  gcp-service-account:
    description: "GCP Service Account Key"
    required: true
    default: "${{ secrets.GCP_SERVICE_ACCOUNT }}"
  gke-cluster:
    description: "GKE Cluster"
    required: true
    default: "${{ secrets.GKE_CLUSTER }}"
  gke-location:
    description: "GKE Location"
    required: true
    default: "${{ secrets.GKE_LOCATION }}"
  skaffold-version:
    description: "Skaffold Version"
    required: true
    default: "1.33.0"

runs:
  using: "composite"
  steps:
    - name: Download build reference
      uses: actions/download-artifact@v2
      with:
        name: build-ref

    - uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        project_id: ${{ inputs.gcp-project-id }}
        service_account_key: ${{ inputs.gcp-service-account }}
        export_default_credentials: true

    - uses: google-github-actions/get-gke-credentials@v0.3.0
      with:
        cluster_name: ${{ inputs.gke-cluster }}
        location: ${{ inputs.gke-location }}

    - uses: yokawasa/action-setup-kube-tools@v0.7.1
      with:
        setup-tools: "skaffold"
        skaffold: "1.32.0"

    - name: Deploy
      run: |
        skaffold deploy --build-artifacts=build.json
